In [1]:
import pandas as pd
import numpy as np

In [2]:
# Lendo a base de dados já com os clusters (não será upada no github devido ao seu tamanho de 250MB)

base_clusters = pd.read_csv(r'Dados/cluster_por_musica.csv')
base_clusters.head()

,0,1,2,3,4,5,6,7,8,9,...,605,606,607,608,609,610,611,cluster_pca,artists,name
0,0.174796,0.731252,2.186797,-0.767192,0.594847,0.315968,-0.412322,-0.479171,-2.700668,2.109956,...,-0.009111,0.005154,-0.034027,-0.032617,-2.060759e-10,2.453309e-10,-4.232451e-11,2,Coldplay,Yellow
1,-1.358420,0.052935,-1.789973,1.938444,0.403606,1.023898,-1.172118,0.821698,-1.716897,0.252498,...,-0.031986,0.029708,-0.016322,-0.030234,-1.529848e-11,1.167974e-10,2.013901e-11,2,OutKast,Ms. Jackson
2,-0.972077,0.658094,0.757500,-0.277350,-0.400393,0.402941,1.292960,1.839192,-1.562236,1.410677,...,0.017097,0.017361,-0.010979,-0.012781,-1.817515e-10,2.316721e-10,-4.433430e-11,2,Linkin Park,In the End
3,-0.926464,1.292091,0.398499,-0.997738,0.202219,0.620859,-0.527689,1.135529,-1.343893,1.020964,...,0.089337,0.164777,-0.064148,-0.040911,-6.271411e-10,1.672884e-09,-2.414475e-10,2,3 Doors Down,Kryptonite
4,-1.710077,-0.383502,-1.258562,1.346428,1.223591,1.744579,0.094311,0.479412,-2.125376,0.389565,...,-0.011937,-0.004081,-0.017478,-0.010033,-5.677863e-11,-2.853156e-11,1.462698e-11,41,Eminem,The Real Slim Shady

In [3]:
# Definindo uma música para sugerir recomendações
artista_exemplo = 'Ed Sheeran'
musica_exemplo = 'Shape of You'

In [4]:
# Verificando o cluster dessa música:
cluster_exemplo = base_clusters.loc[((base_clusters['artists'] == artista_exemplo) & (base_clusters['name'] == musica_exemplo))]['cluster_pca'].values[0]
cluster_exemplo

11

In [5]:
# Verificando as métricas da música exemplo:
metricas_exemplo = base_clusters.loc[((base_clusters['artists'] == artista_exemplo) & (base_clusters['name'] == musica_exemplo))].loc[:, :'611'].values.reshape(-1, 1)

In [6]:
# Adicionando uma coluna ao dataframe que representará a distância euclidiana da música até a Shape of You
base_clusters['Distância Shape of You'] = [np.linalg.norm(metricas_exemplo - base_clusters.loc[i, :'611'].values.reshape(-1, 1)) for i in base_clusters.index]

In [7]:
base_clusters.head()

,0,1,2,3,4,5,6,7,8,9,...,606,607,608,609,610,611,cluster_pca,artists,name,Distância Shape of You
0,0.174796,0.731252,2.186797,-0.767192,0.594847,0.315968,-0.412322,-0.479171,-2.700668,2.109956,...,0.005154,-0.034027,-0.032617,-2.060759e-10,2.453309e-10,-4.232451e-11,2,Coldplay,Yellow,26.534787
1,-1.358420,0.052935,-1.789973,1.938444,0.403606,1.023898,-1.172118,0.821698,-1.716897,0.252498,...,0.029708,-0.016322,-0.030234,-1.529848e-11,1.167974e-10,2.013901e-11,2,OutKast,Ms. Jackson,29.325095
2,-0.972077,0.658094,0.757500,-0.277350,-0.400393,0.402941,1.292960,1.839192,-1.562236,1.410677,...,0.017361,-0.010979,-0.012781,-1.817515e-10,2.316721e-10,-4.433430e-11,2,Linkin Park,In the End,25.356352
3,-0.926464,1.292091,0.398499,-0.997738,0.202219,0.620859,-0.527689,1.135529,-1.343893,1.020964,...,0.164777,-0.064148,-0.040911,-6.271411e-10,1.672884e-09,-2.414475e-10,2,3 Doors Down,Kryptonite,34.675484
4,-1.710077,-0.383502,-1.258562,1.346428,1.223591,1.744579,0.094311,0.479412,-2.125376,0.389565,...,-0.004081,-0.017478,-0.010033,-5.677863e-11,-2.853156e-11,1.462698e-11,41,Eminem,The Real Slim Shady,22.788978

In [13]:
# Verificando as músicas mais "próximas" à música selecionada como exemplo:

base_clusters[['artists', 'name', 'cluster_pca', 'Distância Shape of You']].sort_values(by = ['Distância Shape of You'], ascending=True).head(10)

,artists,name,cluster_pca,Distância Shape of You
2463,Ed Sheeran,Shape of You,11,0.000000
2855,Ed Sheeran,I Don't Care (with Justin Bieber),11,1.030268
5271,Ed Sheeran,South of the Border (feat. Camila Cabello & Ca...,11,1.075704
13369,Ed Sheeran,What Do I Know?,11,1.329361
6958,Ed Sheeran,Sing,11,1.346087
13626,Ed Sheeran,Cross Me (feat. Chance the Rapper & PnB Rock),11,1.525012
15070,Ed Sheeran,Barcelona,11,1.535086
15120,Ed Sheeran,New Man,11,1.603967
5075,Ed Sheeran,Dive,11,1.801667
15107,Ed Sheeran,Nancy Mulligan,11,1.836426